name: boors-azma-platform

services:
  tsetmc-api:
    build:
      context: ../../tsetmc-api
    container_name: tsetmc-api
    ports:
      - "9000:9000"
    restart: unless-stopped

  fipiran-api:
    build:
      context: ../../fipiran-api
    container_name: fipiran-api
    ports:
      - "9001:9001"
    restart: unless-stopped

  codal-api:
    build:
      context: ../../codal-api
    container_name: codal-api
    ports:
      - "9002:9002"
    restart: unless-stopped

  boors-azma-ui:
    build:
      context: ../../boors-azma-ui
    container_name: boors-azma-ui
    ports:
      - "8080:8080"
    depends_on:
      - tsetmc-api
      - fipiran-api
      - codal-api
    restart: unless-stopped
