#!/usr/bin/env bash
# Detect host RAM + CPU and apply a safe resource profile for Docker Compose.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_DIR="$(cd "$SCRIPT_DIR/../compose" && pwd)"
PROFILES_DIR="$COMPOSE_DIR/profiles"
ENV_FILE="$COMPOSE_DIR/.env"

detect_host_memory_mb() {
  if [[ -n "${HOST_MEMORY_MB:-}" ]]; then
    echo "$HOST_MEMORY_MB"
    return 0
  fi

  if [[ -r /proc/meminfo ]]; then
    awk '/MemTotal/ {printf "%d\n", $2 / 1024}' /proc/meminfo
    return 0
  fi

  if command -v sysctl >/dev/null 2>&1; then
    local bytes
    bytes="$(sysctl -n hw.memsize 2>/dev/null || echo 0)"
    echo $((bytes / 1024 / 1024))
    return 0
  fi

  echo 1024
}

detect_host_cpu_cores() {
  if [[ -n "${HOST_CPU_CORES:-}" ]]; then
    echo "$HOST_CPU_CORES"
    return 0
  fi

  if [[ -r /proc/cpuinfo ]]; then
    grep -c ^processor /proc/cpuinfo
    return 0
  fi

  if command -v sysctl >/dev/null 2>&1; then
    sysctl -n hw.ncpu 2>/dev/null || echo 1
    return 0
  fi

  if command -v nproc >/dev/null 2>&1; then
    nproc
    return 0
  fi

  echo 1
}

profile_rank() {
  case "$1" in
    ultra) echo 1 ;;
    low) echo 2 ;;
    standard) echo 3 ;;
    *) echo 0 ;;
  esac
}

choose_profile() {
  local mem_mb="$1"
  local cpu_cores="$2"

  if [[ -n "${RESOURCE_PROFILE:-}" ]]; then
    echo "$RESOURCE_PROFILE"
    return 0
  fi

  # ultra: 1 GB VPS and similar tiny hosts
  if [[ "$mem_mb" -le 1200 ]]; then
    echo ultra
    return 0
  fi

  # low: small RAM hosts, or low-core machines with modest RAM
  if [[ "$mem_mb" -le 2500 ]] || { [[ "$cpu_cores" -le 2 ]] && [[ "$mem_mb" -le 4096 ]]; }; then
    echo low
    return 0
  fi

  # standard: 2.5 GB+ dev/prod hosts (no separate high profile; 8 GB+ uses standard)
  echo standard
}

read_env_profile() {
  if [[ ! -f "$ENV_FILE" ]]; then
    echo ""
    return 0
  fi

  grep -E '^RESOURCE_PROFILE=' "$ENV_FILE" 2>/dev/null \
    | tail -1 \
    | cut -d= -f2- \
    | tr -d ' "'\''\r'
}

is_manual_profile_lock() {
  [[ -f "$ENV_FILE" ]] || return 1
  grep -qE '^RESOURCE_PROFILE_MANUAL=1|^# Manual profile lock' "$ENV_FILE"
}

read_env_header_mem_mb() {
  if [[ ! -f "$ENV_FILE" ]]; then
    echo ""
    return 0
  fi

  grep '^# Host:' "$ENV_FILE" 2>/dev/null \
    | sed -n 's/.* \([0-9][0-9]*\) MB RAM.*/\1/p' \
    | head -1
}

should_auto_apply() {
  local recommended="$1"
  local current="$2"
  local mem_mb="$3"

  if [[ ! -f "$ENV_FILE" ]]; then
    return 0
  fi

  if is_manual_profile_lock; then
    return 1
  fi

  if [[ -z "$current" ]]; then
    return 0
  fi

  local rec_rank cur_rank
  rec_rank="$(profile_rank "$recommended")"
  cur_rank="$(profile_rank "$current")"

  # Host outgrew an overly aggressive profile (e.g. ultra on a 16 GB dev machine).
  if [[ "$cur_rank" -lt "$rec_rank" ]]; then
    return 0
  fi

  if grep -q '^# Auto-generated by configure-resources.sh' "$ENV_FILE"; then
    local header_mem header_profile
    header_mem="$(read_env_header_mem_mb)"
    header_profile="$(grep '^# Host:' "$ENV_FILE" 2>/dev/null | sed -n 's/.*Profile: \([a-z]*\).*/\1/p' | head -1)"

    if [[ -n "$header_profile" && "$header_profile" != "$recommended" ]]; then
      return 0
    fi

    if [[ -n "$header_mem" && "$header_mem" != "$mem_mb" ]]; then
      local diff=0
      if [[ "$mem_mb" -gt "$header_mem" ]]; then
        diff=$((mem_mb - header_mem))
      else
        diff=$((header_mem - mem_mb))
      fi
      if [[ "$diff" -gt 512 ]]; then
        return 0
      fi
    fi
  fi

  return 1
}

write_env_file() {
  local profile="$1"
  local mem_mb="$2"
  local cpu_cores="$3"
  local profile_file="$PROFILES_DIR/${profile}.env"

  {
    echo "# Auto-generated by configure-resources.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo "# Host: ${mem_mb} MB RAM, ${cpu_cores} CPU cores | Profile: ${profile}"
    echo "# To pin a profile manually, add: # Manual profile lock"
    echo ""
    cat "$profile_file"
    echo ""
    echo "# Shared runtime settings"
    echo "SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE=20s"
    echo ""
    echo "# Build memory caps (sequential build uses one service at a time)"
    echo "MAVEN_BUILD_HEAP_MB=384"
    echo "NODE_BUILD_HEAP_MB=256"
    echo "COMPOSE_BUILD_PARALLEL=0"
  } > "$ENV_FILE"
}

usage() {
  cat <<'EOF'
Usage: configure-resources.sh [--profile ultra|low|standard] [--auto] [--force]

Detects host RAM + CPU cores and writes compose/.env from a resource profile.

Profiles (auto-selected):
  ultra    - <= 1.2 GB RAM (1 GB VPS)
  low      - <= 2.5 GB RAM, or <= 2 cores with <= 4 GB RAM
  standard - 2.5 GB+ RAM (including 8 GB+ dev/prod; no separate high profile)

Modes:
  (default)  Show recommendation; keep existing .env unless --force
  --auto     Apply when missing, stale, or mismatched for this host
  --force    Always overwrite compose/.env

Environment overrides:
  RESOURCE_PROFILE=ultra   Force a profile without auto-detection
  HOST_MEMORY_MB=1024      Override detected RAM (for testing)
  HOST_CPU_CORES=1         Override detected CPU cores (for testing)
EOF
}

main() {
  local profile="" force=0 auto=0

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --profile)
        [[ $# -ge 2 ]] || { echo "Missing value for --profile" >&2; exit 1; }
        RESOURCE_PROFILE="$2"
        profile="$2"
        shift 2
        ;;
      --auto)
        auto=1
        shift
        ;;
      --force|-f)
        force=1
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        echo "Unknown option: $1" >&2
        usage
        exit 1
        ;;
    esac
  done

  local mem_mb cpu_cores detected_profile current_profile profile_file
  mem_mb="$(detect_host_memory_mb)"
  cpu_cores="$(detect_host_cpu_cores)"
  detected_profile="$(choose_profile "$mem_mb" "$cpu_cores")"
  profile="${profile:-$detected_profile}"
  profile_file="$PROFILES_DIR/${profile}.env"
  current_profile="$(read_env_profile)"

  if [[ ! -f "$profile_file" ]]; then
    echo "Profile not found: $profile_file" >&2
    exit 1
  fi

  local apply=0
  if [[ "$force" -eq 1 || -n "${RESOURCE_PROFILE:-}" ]]; then
    apply=1
  elif [[ "$auto" -eq 1 ]]; then
    if should_auto_apply "$detected_profile" "$current_profile" "$mem_mb"; then
      profile="$detected_profile"
      profile_file="$PROFILES_DIR/${profile}.env"
      apply=1
    fi
  fi

  if [[ "$apply" -eq 0 ]]; then
    if [[ -f "$ENV_FILE" ]]; then
      echo "Keeping existing $ENV_FILE (profile=${current_profile:-unknown})."
    else
      echo "No compose/.env present; run with --auto or --force to create one."
    fi
    echo "Detected ${mem_mb} MB RAM, ${cpu_cores} CPU cores -> recommended profile: $detected_profile"
    exit 0
  fi

  write_env_file "$profile" "$mem_mb" "$cpu_cores"
  echo "Wrote $ENV_FILE (profile=$profile, host=${mem_mb}MB RAM, ${cpu_cores} cores)"
}

main "$@"
